default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: cloudinary_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: cloudinary__test
  socket: /tmp/mysql.sock
